apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks
  labels:
    app: tasks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasks
  template:
    metadata:
      labels:
        app: tasks
    spec:
      containers:
      - name: tasks
        image: slavayuhymchuk/tasks:1.1
        resources:
          limits:
            cpu: "1"
            memory: "1024Mi"
        ports:
        - containerPort: 80
        envFrom:
        - secretRef:
            name: secret-openai
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: tasks
  name: tasks
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: tasks
  type: LoadBalancer
