apiVersion: v1
kind: Namespace
metadata:
  name: slack
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: slackin-deployment
  namespace: slack # Specify the namespace here
  labels:
    app: slackin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: slackin
  template:
    metadata:
      labels:
        app: slackin
    spec:
      containers:
        - name: slackin
          image: kasmweb/slack
          ports:
            - containerPort: 3000
          env:
            - name: SLACK_API_TOKEN
              value: "xoxb-7609381113681-7609418660081-QEeFrYat9ap2OZ2tknxQxQRV" # Replace with your Slack API token
            - name: SLACK_SUBDOMAIN
              value: "devsecops15workspace" # Replace with your Slack subdomain
            - name: PORT
              value: "3000"

---
apiVersion: v1
kind: Service
metadata:
  name: slackin-service
  namespace: slack # Specify the namespace here
  labels:
    app: slackin
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: slackin
