pipeline {
    agent any
    environment {
        // CODE_CNANGE = getGitChanges()
        VERSION = "1.1"
        DOCKERHUB_CREDS = credentials("dockerhub-accesstoken")
    }
    stages {
        stage ("Build") {
            // when {
            //     expression {
            //         CODE_CNANGE == true
            //     }
            // }
            steps {
                echo "Building docker image version ${VERSION}"
            }
        }
        stage ("Test") {
            steps {
                echo "Testing version ${VERSION}"
            }
        }
        stage ("Push to Docker Hub") {
            steps {
                echo "Authenticating to Docker Hub with ${DOCKERHUB_CREDS}"
                echo "Pushing version ${VERSION} to Docker Hub"
            }
        }
        stage ("Deploy to DEV") {
            when {
                expression {
                    BRANCH_NAME == "dev"
                }
            }
            steps {
                echo "Deploying version ${VERSION} to DEV EKS cluster..."
            }
        }
        stage ("Deploy to PROD") {
            when {
                expression {
                    BRANCH_NAME == "main"
                }
            }
            steps {
                echo "Deploying ${VERSION} to PROD EKS cluster..."
            }
        }
    }
    post {
        always {
            echo "Finished pileline"
        }
        success {
            echo "Success"
        }
        failure {
            echo "Failure"
        }
    }
}
