pipeline {
    agent any
    environment {
        // CODE_CNANGE = getGitChanges()
        VERSION = "1.1" // to get from code
    }
    stages {
        stage ("Build") {
            // when {
            //     expression {
            //         CODE_CNANGE == true
            //     }
            // }
            steps {
                echo "Building docker image version ${VERSION}"
                dir ("Python & Docker/FE") {
                    sh "docker build -t slavayuhymchuk/tasks_fe:${VERSION} . --no-cache"
                    IMAGE_ID = sh "docker images --filter=reference=slavayuhymchuk/tasks_fe:${VERSION} --format '{{.ID}}'"
                    sh "docker tag ${IMAGE_ID} slavayuhymchuk/tasks_fe:latest"
                    // ..
                }
            }
        }
        stage ("Test") {
            steps {
                echo "Testing version ${VERSION}"
            }
        }
        stage ("Push to Docker Hub") {
            steps {
                withCredentials([
                    usernamePassword(credentials: "dockerhub-accesstoken", usernameVariable: USER, passwordVariable: PWD)
                ]) {
                    echo "Pushing version ${VERSION} to Docker Hub"
                    // sh "docker login"
                    // sh "docker push slavayuhymchuk/tasks_fe:${VERSION}"
                    // sh "docker push slavayuhymchuk/tasks_fe:latest"
                }
            }
        }
        stage ("Deploy to DEV") {
            when {
                expression {
                    BRANCH_NAME == "dev"
                }
            }
            steps {
                echo "Deploying version ${VERSION} to DEV EKS cluster..."
            }
        }
        stage ("Deploy to PROD") {
            when {
                expression {
                    BRANCH_NAME == "main"
                }
            }
            steps {
                echo "Deploying ${VERSION} to PROD EKS cluster..."
            }
        }
    }
    post {
        always {
            echo "Finished pileline"
        }
        success {
            echo "Success"
        }
        failure {
            echo "Failure"
        }
    }
}
