apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- tasks-ns.yaml
- tasks-cm.yaml
- sealedsecret-openai.yaml
- sealedsecret-tls-crt.yaml
- sealedsecret-tls-key.yaml
- tasks-be.yaml
- tasks-fe.yaml
