apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks-fe
  namespace: tasks
  labels:
    app: tasks-fe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasks-fe
  template:
    metadata:
      labels:
        app: tasks-fe
    spec:
      containers:
      - name: tasks-fe
        image: slavayuhymchuk/tasks_fe:1.1
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "0.25"
            memory: "256Mi"
          limits:
            cpu: "1"
            memory: "256Mi"
        ports:
        - containerPort: 80
        envFrom:
        - secretRef:
            name: secret-openai
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: tasks-fe
  name: tasks-fe
  namespace: tasks
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: tasks-fe
  type: LoadBalancer
